apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: helmecho
spec:
  type: LoadBalancer
  selector:
    app: echoapp
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
