---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: podinfo-prod
  namespace: prod
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: semver:~0.4
spec:
  releaseName: podinfo-prod
  chart:
    git: git@github.com:fluxcd/helm-operator-get-started
    path: charts/podinfo
    ref: master
  values:
    image:
      repository: stefanprodan/podinfo
      tag: 0.4.11
    replicaCount: 3
# =======
#     app:
#       image: kfirosb/podinfo
#       tag: dev-rraey5ct
#       replicaCount: 1
#     namespace: "prod"
#     hpa:
#       enabled: false
# >>>>>>> e0a4ca4303c8041272ca473714b35f34958c597a
