apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoapp-deployment
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: echoapp
  replicas: 2
  template: 
    metadata:
      labels:
        app: echoapp
    spec:
      containers:
      - name: echoapp
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}" 
        # imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
        - name: MONGODBURL
          valueFrom:
            configMapKeyRef:
              name: mongodb-configmap
              key:  mongodburl
        - name:  PERSIST
          valueFrom:
            configMapKeyRef:
              name: mongodb-configmap
              key:  persist
        - name:  LOGLEVEL
          valueFrom:
            configMapKeyRef:
              name: mongodb-configmap
              key:  loglevel   
