apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echo-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"    
    cert-manager.io/issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - cowsaywtf.tk
    secretName: kfirsecret
  rules:
  - host: cowsaywtf.tk
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: echoserv
            port:
              number: 80

